spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

jwt:
  access-token-secret: 7JwYZKR+cIr3kjEi+k4LuvPzt6aCe42F4t81tHnz5kpf2eKjFP0Gpwbmnh7kmvwXhyfnHJLALTQaZ6pALSfusg==
  refresh-token-secret: Ro/aTqrDEcYQUsiV9MHLISi2xPy0w0BtJm/3SClP7GhS2V4M/gt/1DplbGFzYbNE6JdVhkyNQvcvnDZkofUjsg==
  access-token-expiration-time: 3600000
  refresh-token-expiration-time: 1296000000 # 15일

logging:
  level:
    com.hgleeee.blog: debug

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true